---
apiVersion: v1
kind: Secret
metadata:
  name: data-connection-minio
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: minio-data-connection-s3
