apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sd-kserve
spec:
  predictor:
     storage:
        key: minio-data-connection-name
        path: model_path_at_s3_endpoint
