apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sd-kserve
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: pytorch
      name: ""
      resources:
        limits:
          cpu: "8"
          memory: 10Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "4"
          memory: 8Gi
          nvidia.com/gpu: "1"
      runtime: sd-kserve
      storage:
        key: placeholder
        path: placeholder
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
